# Generated by Django 4.0.3 on 2023-04-15 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliateplan',
            old_name='cookie_expiry_days',
            new_name='cookie_expiration',
        ),
    ]
