# Generated by Django 4.0.3 on 2023-04-15 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_mailgunapifailure_to_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiliate', '0002_rename_cookie_expiry_days_affiliateplan_cookie_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatepartner',
            name='amount_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signup', models.DateTimeField(auto_now_add=True)),
                ('affiliate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.affiliatepartner')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_clciked', models.DateTimeField(auto_now_add=True)),
                ('affiliate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.affiliatepartner')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliatePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.affiliatepartner')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.payment')),
            ],
        ),
    ]
