# Generated by Django 4.0.3 on 2023-04-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_alter_affiliatepartner_amount_payable_signup_clicks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clicks',
            old_name='date_clciked',
            new_name='date_clicked',
        ),
    ]
