# Generated by Django 4.0.3 on 2023-04-15 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0004_rename_date_clciked_clicks_date_clicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatepurchase',
            name='date_purchased',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
