# Generated by Django 4.0.3 on 2023-04-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0005_affiliatepurchase_date_purchased'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliatepartner',
            old_name='affiliate_code',
            new_name='ref_code',
        ),
    ]
