# Generated by Django 4.0.3 on 2023-04-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0007_rename_clicks_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateplan',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5),
        ),
    ]
