# Generated by Django 4.0.3 on 2023-04-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0008_affiliateplan_commission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliateplan',
            old_name='commission',
            new_name='commission_rate',
        ),
    ]
