# Generated by Django 4.0.3 on 2023-04-17 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('affiliate', '0009_rename_commission_affiliateplan_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='session_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
        migrations.AlterField(
            model_name='affiliatepartner',
            name='cookie_value',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
