# Generated by Django 4.0.3 on 2023-04-17 02:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiliate', '0011_rename_click_referralclick'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='ReferralSignUp',
        ),
    ]
