# Generated by Django 4.0.3 on 2023-04-17 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiliate', '0013_rename_affiliatepurchase_referralpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralsignup',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
