# Generated by Django 4.0.3 on 2023-04-17 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0014_alter_referralsignup_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralclick',
            name='session_id',
        ),
    ]
