# Generated by Django 4.0.3 on 2023-04-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0015_remove_referralclick_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralclick',
            name='cookie_value',
            field=models.CharField(default='12345678901234567890123456789012', max_length=32),
            preserve_default=False,
        ),
    ]
