# Generated by Django 4.0.3 on 2023-04-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0016_referralclick_cookie_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralclick',
            name='cookie_value',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
