# Generated by Django 4.0.3 on 2023-04-18 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0017_alter_referralclick_cookie_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliatepartner',
            old_name='cookie_value',
            new_name='cookie_signer',
        ),
    ]
