# Generated by Django 4.0.3 on 2023-04-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0020_remove_referralpurchase_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralpurchase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
